INSERT INTO DEVICE_TYPE VALUES('WW', 'Windows Workstation');
INSERT INTO DEVICE_TYPE VALUES('WS', 'Windows Server');
INSERT INTO DEVICE_TYPE VALUES('MAC', 'Mac');
INSERT INTO SVC VALUES('DEVICE', 4, 'Device');
INSERT INTO SVC VALUES('WIN_ANTIVIRUS', 5, 'Windows Antivirus');
INSERT INTO SVC VALUES('MAC_ANTIVIRUS', 7, 'Mac Antivirus');
INSERT INTO SVC VALUES('BACKUP', 3, 'Backup');
INSERT INTO SVC VALUES('PSA', 2, 'PSA');
INSERT INTO SVC VALUES('SCREEN_SHARE', 1, 'Screen Share');
